/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const NoteId = IDL.Text;
export const Time = IDL.Int;
export const ReminderId = IDL.Text;
export const Note = IDL.Record({
  'id' : NoteId,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : Time,
});
export const Reminder = IDL.Record({
  'id' : ReminderId,
  'scheduledTime' : Time,
  'createdAt' : Time,
  'text' : IDL.Text,
  'isTriggered' : IDL.Bool,
});

export const idlService = IDL.Service({
  'createNote' : IDL.Func([IDL.Text, IDL.Text], [NoteId], []),
  'createReminder' : IDL.Func([IDL.Text, Time], [ReminderId], []),
  'deleteNote' : IDL.Func([NoteId], [], []),
  'deleteReminder' : IDL.Func([ReminderId], [], []),
  'getAllNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
  'getAllReminders' : IDL.Func([], [IDL.Vec(Reminder)], ['query']),
  'getNote' : IDL.Func([NoteId], [Note], ['query']),
  'getPendingReminders' : IDL.Func([], [IDL.Vec(Reminder)], ['query']),
  'getReminder' : IDL.Func([ReminderId], [Reminder], ['query']),
  'markReminderTriggered' : IDL.Func([ReminderId], [], []),
  'updateNote' : IDL.Func([NoteId, IDL.Text, IDL.Text], [], []),
  'updateReminder' : IDL.Func([ReminderId, IDL.Text, Time], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const NoteId = IDL.Text;
  const Time = IDL.Int;
  const ReminderId = IDL.Text;
  const Note = IDL.Record({
    'id' : NoteId,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : Time,
  });
  const Reminder = IDL.Record({
    'id' : ReminderId,
    'scheduledTime' : Time,
    'createdAt' : Time,
    'text' : IDL.Text,
    'isTriggered' : IDL.Bool,
  });
  
  return IDL.Service({
    'createNote' : IDL.Func([IDL.Text, IDL.Text], [NoteId], []),
    'createReminder' : IDL.Func([IDL.Text, Time], [ReminderId], []),
    'deleteNote' : IDL.Func([NoteId], [], []),
    'deleteReminder' : IDL.Func([ReminderId], [], []),
    'getAllNotes' : IDL.Func([], [IDL.Vec(Note)], ['query']),
    'getAllReminders' : IDL.Func([], [IDL.Vec(Reminder)], ['query']),
    'getNote' : IDL.Func([NoteId], [Note], ['query']),
    'getPendingReminders' : IDL.Func([], [IDL.Vec(Reminder)], ['query']),
    'getReminder' : IDL.Func([ReminderId], [Reminder], ['query']),
    'markReminderTriggered' : IDL.Func([ReminderId], [], []),
    'updateNote' : IDL.Func([NoteId, IDL.Text, IDL.Text], [], []),
    'updateReminder' : IDL.Func([ReminderId, IDL.Text, Time], [], []),
  });
};

export const init = ({ IDL }) => { return []; };